---

- name: Build war
  hosts: build
  become: yes

  vars_prompt:
    - name: "githubuser"
      prompt: "Enter your github username"
      private: no
    - name: "githubpassword"
      prompt: "Enter your github password"
      private: yes

  tasks:
    - name: install wget maven git python-pexpect
      apt:
        pkg:
          - wget
          - maven
          - git
          - python-pexpect
    - name: git clone project from github
      git:
        repo: https://github.com/boxfuse/boxfuse-sample-java-war-hello.git
        dest: /boxfuse
        version: master
#       accept_hostkey: yes
    - name: Maven package
      shell: "mvn package -f /boxfuse/pom.xml"
         #Git
    - name: git add
      shell: "git add ."
      args:
        chdir: /boxfuse/target
    - name: git remote add
      ignore_errors: True
      shell: "git remote add origin https://github.com/Xiblex/DZ.git"
      args:
        chdir: /boxfuse/target
    - name: git init
      shell: "git init"
      args:
        chdir: /boxfuse/target
    - name: git config core.sparsecheckout true
      shell: "git config core.sparsecheckout true"
      args:
        chdir: /boxfuse/target
    - name: Git sub directory
      shell: echo "Lesson_8/war/*" >> .git/info/sparse-checkout
      args:
        chdir: /boxfuse/target
#   - name: Git - commiting
#       shell: git init
#       args:
#         chdir: /boxfuse/target
    - name: Git - push
      expect:
        command: git push
        responses:
          Username: "{{ githubuser }}" # Username is a regex
          Password: "{{ githubpassword }}" # Password is a regex
        chdir: "/boxfuse/target"

