---
version: '3'
services:
  buildapp:
    build: buildapp
    volumes:
     - /etc/share:/boxfuse/boxfuse-sample-java-war-hello/target

#  buildtomcat:
#    build: buildtomcat
#    volumes:
#     - /etc/share:/usr/local/tomcat/webapps
#    ports:
#     - "8080:8080"

#  volumes:
#     share:
