---
version: '3'
services:
  buildapp:
    build: buildapp
    volumes:
     - /etc/share:/boxfuse/boxfuse-sample-java-war-hello/target

  prod:
    build: buildtomcat
    volumes:
      - type: volume
        source: /etc/share
        target: /usr/local/tomcat/webapps
      depends_on:
         - build
      ports:
         - "8080:8080"

#  volumes:
#     share:
