---
version: '3'
volumes:
  share:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/inst1/lesson_6/Lesson_7/share
services:
  buildapp:
    build: buildapp
    volumes:
      - share:/boxfuse/target
#      - /home/inst1/lesson_6/Lesson_7/share:/boxfuse/target

  buildtomcat:
    build: buildtomcat
    volumes:
     - share:/usr/local/tomcat/webapps
    ports:
     - "8080:8080"

#  volumes:
#     share:
