---
version: '3'
volumes:
  share:
services:
  buildapp:
    build: buildapp
    volumes:
      - ./share:/boxfuse/target

#  buildtomcat:
#    build: buildtomcat
#    volumes:
#     - /share:/usr/local/tomcat/webapps
#    ports:
#     - "8080:8080"

#  volumes:
#     share:
